$schema = {

  ims_asset_accessed: {
    # created
    asset_accessed_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 11 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 24 },
    object_type: { type: 'string', size: 25 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 15 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_asset_type: { type: 'string', size: 24 },
    object_asset_subtype: { type: 'string', size: 24 }
  },

  ims_assignment_created: {
    # created
    assignment_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 255, mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_datecreated: { type: 'datetime' },
    object_maxscore_numberstr: { type: 'float', size: 53 },
    object_description: { type: 'string', size: 'MAX', mbstr: true },
    object_lock_at: { type: 'datetime' },
    object_datetoshow: { type: 'datetime' },
    object_datetosubmit: { type: 'datetime' },
  },

  ims_assignment_updated: {
    # created
    assignment_updated_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 8 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 255, mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    context: { type: 'string', size: 42 },
    # specific
    object_description: { type: 'string', size: 'MAX', mbstr: true },
    object_datemodified: { type: 'datetime' },
    object_workflow_state: { type: 'string', size: 11 },
    object_datetosubmit: { type: 'datetime' },
    object_maxscore_numberstr: { type: 'float', size: 53 },
    object_lock_at: { type: 'datetime' },
    object_datetoshow: { type: 'datetime' },
  },

  ims_attachment_created: {
    # created
    attachment_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 'MAX', mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_datecreated: { type: 'datetime' },
    object_context_id: { type: 'bigint' },
    object_context_type: { type: 'string', size: 6 },
    object_filename: { type: 'string', size: 'MAX', mbstr: true },
    object_folder_id: { type: 'bigint' },
    object_mediatype: { type: 'string', size: 255 }
  },

  ims_attachment_deleted: {
    # created
    attachment_deleted_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 'MAX', mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_datemodified: { type: 'datetime' },
    object_context_id: { type: 'bigint' },
    object_context_type: { type: 'string', size: 6 },
    object_filename: { type: 'string', size: 'MAX', mbstr: true },
    object_folder_id: { type: 'bigint' },
    object_mediatype: { type: 'string', size: 255 }
  },

  ims_attachment_updated: {
    # created
    attachment_updated_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 8 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 'MAX', mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_datemodified: { type: 'datetime' },
    object_context_id: { type: 'bigint' },
    object_context_type: { type: 'string', size: 6 },
    object_filename: { type: 'string', size: 'MAX', mbstr: true },
    object_folder_id: { type: 'bigint' },
    object_mediatype: { type: 'string', size: 255 }
  },

  ims_course_created: {
    # created
    course_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 255 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_discussion_entry_created: {
    # created
    discussion_entry_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 6 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 12 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_ispartof_id: { type: 'string', size: 100 },
    object_ispartof_type: { type: 'string', size: 6 },
    object_body: { type: 'string', size: 'MAX' },
  },

  ims_discussion_topic_created: {
    # created
    discussion_topic_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 255, mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 11 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_is_announcement: { type: 'string', size: 5 }
  },

  ims_enrollment_created: {
    # created
    enrollment_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_datecreated: { type: 'datetime' },
    object_course_id: { type: 'string', size: 100 },
    object_course_section_id: { type: 'string', size: 100 },
    object_limit_privileges_to_course_section: { type: 'string', size: 5 },
    object_user_id: { type: 'string', size: 100 },
    object_user_name: { type: 'string', size: 255 },
    object_workflow_state: { type: 'string', size: 16 },
    membership_organization_suborganizationof_id: { type: 'string', size: 100 },
    membership_organization_suborganizationof_type: { type: 'string', size: 14 }
  },

  ims_enrollment_state_created: {
    # created
    enrollment_state_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_access_is_current: { type: 'string', size: 5 },
    object_restricted_access: { type: 'string', size: 5 },
    object_state: { type: 'string', size: 16 },
    object_state_is_current: { type: 'string', size: 255 },
    object_state_valid_until: { type: 'datetime' },
    object_startedattime: { type: 'datetime' },
  },

  ims_enrollment_state_updated: {
    # created
    enrollment_state_updated_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 8 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_access_is_current: { type: 'string', size: 255 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_restricted_access: { type: 'string', size: 255 },
    object_startedattime: { type: 'datetime' },
    object_state_is_current: { type: 'string', size: 255 },
    object_state_valid_until: { type: 'datetime' },
    object_state: { type: 'string', size: 16 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_enrollment_updated: {
    # created
    enrollment_updated_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 8 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_suborganizationof_id: { type: 'string', size: 100 },
    membership_organization_suborganizationof_type: { type: 'string', size: 14 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_course_id: { type: 'string', size: 100 },
    object_course_section_id: { type: 'string', size: 100 },
    object_datecreated: { type: 'datetime' },
    object_datemodified: { type: 'datetime' },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_limit_privileges_to_course_section: { type: 'string', size: 255 },
    object_type: { type: 'string', size: 100 },
    object_user_id: { type: 'string', size: 100 },
    object_user_name: { type: 'string', size: 255 },
    object_workflow_state: { type: 'string', size: 9 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_grade_change: {
    # created
    grade_change_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 6 },
    actor_id: { type: 'string', size: 100 },
    actor_type: { type: 'string', size: 19 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    generated_attempt_assignable_id: { type: 'string', size: 100 },
    generated_attempt_assignable_type: { type: 'string', size: 25 },
    generated_attempt_assignee_id: { type: 'string', size: 100 },
    generated_attempt_assignee_sis_id: { type: 'string', size: 32 },
    generated_attempt_assignee_type: { type: 'string', size: 6 },
    generated_attempt_grade: { type: 'string', size: 255 },
    generated_attempt_id: { type: 'string', size: 100 },
    generated_attempt_type: { type: 'string', size: 7 },
    generated_entity_id: { type: 'bigint' },
    generated_grade: { type: 'string', size: 255 },
    generated_id: { type: 'string', size: 100 },
    generated_maxscore_numberstr: { type: 'float', size: 53 },
    generated_maxscore: { type: 'float', size: 53 },
    generated_scoredby: { type: 'string', size: 100 },
    generated_scoregiven_numberstr: { type: 'float', size: 53 },
    generated_scoregiven: { type: 'float', size: 53 },
    generated_type: { type: 'string', size: 5 },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_assignable_id: { type: 'string', size: 100 },
    object_assignable_type: { type: 'string', size: 25 },
    object_assignee_id: { type: 'string', size: 100 },
    object_assignee_sis_id: { type: 'string', size: 32 },
    object_assignee_type: { type: 'string', size: 6 },
    object_entity_id: { type: 'bigint' },
    object_grade: { type: 'string', size: 255 },
    object_id: { type: 'string', size: 100 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 10 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_group_created: {
    # created
    group_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_ispartof_id: { type: 'string', size: 100 },
    object_ispartof_name: { type: 'string', size: 255 },
    object_ispartof_type: { type: 'string', size: 255 },
    object_name: { type: 'string', size: 255 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_group_category_created: {
    # created
    group_category_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_id: { type: 'string', size: 100 },
    actor_entity_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 255 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_group_membership_created: {
    # created
    group_membership_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    hostname: { type: 'string', size: 100 },
    object_id: { type: 'string', size: 100 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
    object_member_id: { type: 'string', size: 100 },
    object_member_type: { type: 'string', size: 6 },
    object_organization_entity_id: { type: 'bigint' },
    object_organization_id: { type: 'string', size: 100 },
    object_organization_ispartof_id: { type: 'string', size: 100 },
    object_organization_ispartof_name: { type: 'string', size: 255 },
    object_organization_ispartof_type: { type: 'string', size: 6 },
    object_organization_name: { type: 'string', size: 255 },
    object_organization_type: { type: 'string', size: 5 }
  },

  ims_logged_in: {
    # created
    logged_in_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 8 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    hostname: { type: 'string', size: 100 },
    object_id: { type: 'string', size: 100 },
    object_redirect_url: { type: 'string', size: 'MAX' },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 12 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_logged_out: {
    # created
    logged_out_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 9 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    hostname: { type: 'string', size: 100 },
    object_id: { type: 'string', size: 100 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 12 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_quiz_submitted: {
    # created
    quiz_submitted_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 9 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_assignable_id: { type: 'string', size: 100 },
    object_assignable_type: { type: 'string', size: 25 },
    object_assignee_id: { type: 'string', size: 100 },
    object_assignee_type: { type: 'string', size: 6 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 15 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_submission_created: {
    # created
    submission_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 9 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_assignable_id: { type: 'string', size: 100 },
    object_assignable_type: { type: 'string', size: 25 },
    object_assignee_id: { type: 'string', size: 100 },
    object_assignee_type: { type: 'string', size: 6 },
    object_body: { type: 'string', size: 'MAX' },
    object_count: { type: 'INT' },
    object_datecreated: { type: 'datetime' },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_submission_type: { type: 'string', size: 24 },
    object_type: { type: 'string', size: 100 },
    object_url: { type: 'string', size: 'MAX' },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 15 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },


  ims_submission_updated: {
    # created
    submission_updated_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 8 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_assignable_id: { type: 'string', size: 100 },
    object_assignable_type: { type: 'string', size: 25 },
    object_assignee_id: { type: 'string', size: 100 },
    object_assignee_type: { type: 'string', size: 6 },
    object_body: { type: 'string', size: 'MAX' },
    object_count: { type: 'INT' },
    object_datemodified: { type: 'datetime' },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_submission_type: { type: 'string', size: 24 },
    object_type: { type: 'string', size: 100 },
    object_url: { type: 'string', size: 'MAX' },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_syllabus_updated: {
    # created
    syllabus_updated_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 8 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    hostname: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_type: { type: 'string', size: 10 },
    object_body: { type: 'string', size: 'MAX' },
    object_creators_id: { type: 'string', size: 100 },
    object_creators_type: { type: 'string', size: 6 },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 8 },
    object_type: { type: 'string', size: 8 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_user_account_association_created: {
    # created
    user_account_association_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_real_user_id: { type: 'bigint' },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_datecreated: { type: 'datetime' },
    object_datemodified: { type: 'datetime' },
    object_id: { type: 'string', size: 100 },
    object_is_admin: { type: 'string', size: 5 },
    object_type: { type: 'string', size: 100 },
    object_user_id: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_wiki_page_created: {
    # created
    wiki_page_created_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_body: { type: 'string', size: 'MAX' },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 255, mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_wiki_page_deleted: {
    # created
    wiki_page_deleted_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 7 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 255, mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },

  ims_wiki_page_updated: {
    # created
    wiki_page_updated_id: { type: 'bigint', primary_key: true },
    processed_at: { type: 'datetime' },
    event_time_local: { type: 'datetime' },
    # shared
    uuid: { type: 'string', size: 45 },
    action: { type: 'string', size: 8 },
    actor_entity_id: { type: 'bigint' },
    actor_id: { type: 'string', size: 100 },
    actor_root_account_id: { type: 'bigint' },
    actor_root_account_lti_guid: { type: 'string', size: 40 },
    actor_root_account_uuid: { type: 'string', size: 40 },
    actor_type: { type: 'string', size: 19 },
    actor_user_login: { type: 'string', size: 100 },
    context: { type: 'string', size: 42 },
    edapp_id: { type: 'string', size: 100 },
    edapp_type: { type: 'string', size: 19 },
    eventtime: { type: 'datetime' },
    group_context_type: { type: 'string', size: 6 },
    group_entity_id: { type: 'bigint' },
    group_id: { type: 'string', size: 100 },
    group_type: { type: 'string', size: 24 },
    hostname: { type: 'string', size: 100 },
    job_id: { type: 'bigint' },
    job_tag: { type: 'string', size: 100 },
    membership_id: { type: 'string', size: 124 },
    membership_member_id: { type: 'string', size: 100 },
    membership_member_type: { type: 'string', size: 6 },
    membership_organization_id: { type: 'string', size: 100 },
    membership_organization_type: { type: 'string', size: 14 },
    membership_roles: { type: 'string', size: 24 },
    membership_type: { type: 'string', size: 10 },
    object_body: { type: 'string', size: 'MAX' },
    object_entity_id: { type: 'bigint' },
    object_id: { type: 'string', size: 100 },
    object_name: { type: 'string', size: 255, mbstr: true },
    object_type: { type: 'string', size: 100 },
    request_id: { type: 'string', size: 36 },
    session_id: { type: 'string', size: 63 },
    session_type: { type: 'string', size: 7 },
    type: { type: 'string', size: 5 },
    user_agent: { type: 'string', size: 255 },
    version: { type: 'string', size: 12 },
    # specific
  },
}